#!/usr/bin/env node
/**
 * CLI Tool: Generate Administrator Credentials for Divya Rao's Private Studio
 * Usage: node scripts/create-admin.js [email] [password]
 */
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const email = process.argv[2] || 'admin@divyarao.in';
const password = process.argv[3];

if (!password) {
  console.log('\n=== Private Studio: Admin Account Generator ===');
  console.log('Usage: node scripts/create-admin.js <email> <password>\n');
  console.log('Example: node scripts/create-admin.js divya@example.com MyStrongSecretPassword#2026\n');
  process.exit(1);
}

const saltRounds = 12;
const hash = bcrypt.hashSync(password, saltRounds);
const sessionSecret = crypto.randomBytes(48).toString('hex');

const envPath = path.join(rootDir, '.env');

// Read existing .env to preserve MONGODB_URI or other custom settings
let existingMongo = '';
if (fs.existsSync(envPath)) {
  const existing = fs.readFileSync(envPath, 'utf8');
  const mongoMatch = existing.match(/^MONGODB_URI=(.+)$/m);
  if (mongoMatch) {
    existingMongo = mongoMatch[1].trim();
  }
}

const envContent = `# Server Environment Variables (Auto-generated by scripts/create-admin.js)
PORT=3000
NODE_ENV=development
ADMIN_EMAIL=${email}
ADMIN_PASSWORD_HASH=${hash}
SESSION_SECRET=${sessionSecret}
DATA_DIR=server/data
${existingMongo ? `MONGODB_URI=${existingMongo}\n` : ''}`;

fs.writeFileSync(envPath, envContent, 'utf8');

console.log('\n✓ Administrator credentials securely hashed and saved to .env');
console.log(`  Admin Email: ${email}`);
console.log(`  Bcrypt Hash (cost factor ${saltRounds}): ${hash}`);
console.log(`  Session Secret: ${sessionSecret.slice(0, 10)}...`);
console.log('\nYour .env is protected by .gitignore and will NEVER be committed to GitHub.\n');
